# Generated by Django 3.0.5 on 2020-05-03 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_address_final',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address_final',
        ),
        migrations.RemoveField(
            model_name='order',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated',
        ),
        migrations.DeleteModel(
            name='ProductPurchase',
        ),
    ]
